# Generated by Django 6.0.2 on 2026-04-26 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='artworks/', verbose_name='Image')),
                ('category', models.CharField(choices=[('Painting', 'Peinture'), ('Photography', 'Photographie'), ('Digital', 'Art Digital'), ('Mixed', 'Technique Mixte'), ('Sculpture', 'Sculpture'), ('Drawing', 'Dessin')], default='Painting', max_length=20)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Année de création')),
                ('medium', models.CharField(blank=True, max_length=100, verbose_name='Technique')),
                ('views_count', models.IntegerField(default=0, verbose_name='Vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Œuvre',
                'verbose_name_plural': 'Œuvres',
                'ordering': ['-created_at'],
            },
        ),
    ]
